Repository MartinFillon/42zsh, pull requests merged in 2023-05, with the labels that each got.

#54 feat: add history builtin + .history file at root
  Makefile
  include/mysh/builtins.h
  include/mysh/history.h
  include/mysh/mysh.h
  src/builtins/builtins.c
  src/builtins/history.c
  src/input/history.c
  src/input/read.c
  src/main.c
Labels: feature, builtin, enhancement

#56 feat: add (simple) alias / unalias builtins
  Makefile
  include/mysh/builtins.h
  include/mysh/mysh.h
  src/builtins/alias.c
  src/builtins/builtins.c
  src/builtins/unalias.c
  src/exec/tree.c
  src/main.c
Labels: feature, enhancement, aliases

#69 feat: :sparkles: (!) feature before exec + fix: history placement
  Makefile
  include/my_str.h
  include/mysh/builtins.h
  include/mysh/history.h
  include/mysh/parser.h
  lib/my_str/idx_ops.c
  src/builtins/history.c
  src/input/backticks.c
  src/input/exclamation.c
  src/input/read.c
  src/input/subshell.c
  src/input/variables.c
  src/parser/gen.c
Labels: feature, enhancement

#82 feat: :sparkles: link of history to termios
  include/mysh/termios.h
  src/input/exclamation.c
  src/line_editing/arrow.c
  src/line_editing/manage_input.c
  src/line_editing/read_termios.c
  src/line_editing/termios.c
Labels: feature, enhancement, line edition

#89 fix: !! handled for every line + feat: load of .history
  Makefile
  include/mysh/history.h
  src/builtins/history.c
  src/input/exclamation.c
  src/input/manage_files.c
  src/input/read.c
Labels: bug, enhancement

#90 86 scripting - BONUS if and foreach
  .gitignore
  Makefile
  bonus/tester.py
  bonus/tests.json
  src/builtins/echo.c
  src/builtins/scripting/foreach.c
  src/builtins/scripting/foreach/executor.c
  src/builtins/scripting/foreach/foreach.c
  src/builtins/scripting/if.c
  src/builtins/scripting/repeat.c
  src/builtins/where.c
  src/exec/exec.c
  src/exec/jobs.c
  src/input/globbings.c
  src/input/read.c
  src/input/split_args.c
  src/main.c
  src/middleware/read_file.c
Labels: feature, builtin

#94 feat: :zap: improvements of history builtin w flags
  bonus/tests.json
  include/mysh/history.h
  src/builtins/history.c
  src/input/history.c
  src/input/manage_files.c
Labels: enhancement

#95 fix: :bug: memory leak for clean + feat: :sparkles: !# in exclamation
  include/mysh/history.h
  src/builtins/history.c
  src/input/exclamation.c
  src/input/manage_files.c
Labels: enhancement

#96 fix: :bug: !# dead space handled
  src/input/exclamation.c
Labels: bug, enhancement

#97 fix: :bug: leak memory detected for !# input
  bonus/tests.json
  src/input/exclamation.c
Labels: bug, enhancement
